sudo: required
language: java
jdk:
  - openjdk11


addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5
      - postgresql-client-9.5

env:
  global:
    - PGPORT=5432
    - PGHOST=localhost



services:
  - postgresql

before_script:
  - psql -c 'create database wsboard_test;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin217';" -U postgres


script: mvn clean install -DskipTests=false