sudo: required
language: java
jdk:
  - openjdk11


addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6
      - postgresql-client-9.6

env:
  global:
    - PGPORT=5432
    - PGHOST=localhost
    - NODE_VERSION=10.15.3


services:
  - postgresql

before_script:
  - psql -c 'create database wsboard_test;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin217';" -U postgres


cache:
  directories:
  - node_modules
  

script: mvn clean install

after_success:
  - mvn clean test
