sudo: required
matrix:
  - language: java
     jdk: openjdk11
  - language: node_js
    node_js: 10.15.3



addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6
      - postgresql-client-9.6

env:
  global:
    - PGPORT=5432
    - PGHOST=localhost



services:
  - postgresql

before_script:
  - psql -c 'create database wsboard_test;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin217';" -U postgres

#before_install:
#  - sudo python3 -m smtpd -n -c DebuggingServer localhost:25

script: mvn clean install -DskipTests=false
