language: java
jdk:
  - openjdk11

#addons:
#  postgresql: "10"
#  apt:
#    packages:
#      - postgresql-10
#      - postgresql-client-10
#env:
#    global:
#      - PGPORT=5433

services:
  - postgresql


before_script:
  - psql -c 'create database wsboard_test;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin217';" -U postgres


script: mvn clean install -DskipTests=false