version: '3'
services:
  wsb-app:
    image: abondar/wsb-app
    # Link to containers in another service
    links:
      - db
      - wsb-email
    volumes:
      - $PWD
    networks:
      - wsbnet


  srv:
    image: abondar/wsb-srv

    ports:
      - 80:80
    links:
      - wsb-email
      - wsb-app
    networks:
      - wsbnet


  wsb-email:
     image: juanluisbaptiste/postfix
     restart: always

     ports:
       - 25:25

     environment:
       SMTP_PORT: 25
       SERVER_HOSTNAME: wsb-email.tk
       SMTP_SERVER: smtp.gmail.com
       SMTP_USERNAME: admin
       SMTP_PASSWORD: admin217

     networks:
       - wsbnet

  db:
     image: postgres:9.6
     restart: always
     environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin217
        POSTGRES_DB: wsboard
     networks:
       - wsbnet


networks:
  wsbnet:
    driver: "bridge"
