apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: base
spec:
  rules:
     #for nginxinc controller host should be set
    - http:
        paths:
          - path: /
            backend:
              serviceName: base
              servicePort: 8024
